// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'community.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDtdw-fHe9O21qZboGObwixGwVUaKtEuI',
    appId: '1:200040656841:android:818105d452a7119c8e8218',
    messagingSenderId: '200040656841',
    projectId: 'write-story-308919',
    storageBucket: 'write-story-308919.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAShE05uKEZEUM5Kk13jkJbbb4D_8R6-wA',
    appId: '1:200040656841:ios:ca1781a9ba2a6f1b8e8218',
    messagingSenderId: '200040656841',
    projectId: 'write-story-308919',
    storageBucket: 'write-story-308919.firebasestorage.app',
    iosBundleId: 'com.tc.writestory.community',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAShE05uKEZEUM5Kk13jkJbbb4D_8R6-wA',
    appId: '1:200040656841:ios:ca1781a9ba2a6f1b8e8218',
    messagingSenderId: '200040656841',
    projectId: 'write-story-308919',
    storageBucket: 'write-story-308919.firebasestorage.app',
    iosBundleId: 'com.tc.writestory.community',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ZVGvpfpM8MYKXRZTgP4ma2Gr2Hb8jZE',
    appId: '1:200040656841:web:dc7e0bbbf6c93b838e8218',
    messagingSenderId: '200040656841',
    projectId: 'write-story-308919',
    authDomain: 'write-story-308919.firebaseapp.com',
    storageBucket: 'write-story-308919.firebasestorage.app',
    measurementId: 'G-PP2C5GYNGD',
  );

}
