import 'dart:async';

import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:storypad/core/objects/backup_file_object.dart';
import 'package:storypad/core/objects/backup_object.dart';
import 'package:storypad/core/objects/device_info_object.dart';
import 'package:storypad/core/services/backup_sync_steps/backup_importer_service.dart';
import 'package:storypad/core/services/backup_sync_steps/backup_sync_message.dart';
import 'package:storypad/core/services/backup_sync_steps/utils/restore_backup_service.dart';

import 'backup_importer_service_test.mocks.dart'; // Generated by mockito

// Generate a Mock class for RestoreBackupService
@GenerateMocks([RestoreBackupService])
void main() {
  group('BackupImporterService', () {
    late BackupImporterService backupImporterService;
    late MockRestoreBackupService mockRestoreBackupService;

    setUp(() {
      mockRestoreBackupService = MockRestoreBackupService();
      backupImporterService = BackupImporterService(
        restoreService: mockRestoreBackupService,
      );
    });

    tearDown(() {
      // Ensure the controller is closed after each test to prevent resource leaks
      backupImporterService.controller.close();
    });

    test('start with null backup should emit success message and not call restoreService', () async {
      // Create a completer to know when the expected message has been received
      final completer = Completer<void>();

      // Listen to the stream and complete the completer when the expected message arrives
      backupImporterService.message.listen(expectAsync1((message) {
        expect(message, isA<BackupSyncMessage>());
        expect(message!.processing, isFalse);
        expect(message.success, isTrue);
        expect(message.message, 'No new data to import.');
        completer.complete();
      }));

      // Call the method under test
      final result = await backupImporterService.start(null);

      // Wait for the completer to complete, indicating the message was received
      await completer.future;

      expect(result, isTrue);
      verifyZeroInteractions(mockRestoreBackupService);
    });

    test('start with valid backup should emit processing and success messages', () async {
      final testBackupObject = BackupObject(
        tables: {
          'notes': [
            {'id': '1', 'title': 'Test Note'}
          ]
        },
        fileInfo: BackupFileObject(
          createdAt: DateTime.now(),
          device: DeviceInfoObject('Test Device', 'device_id_123'),
        ),
      );
      const int changesCount = 5;

      when(mockRestoreBackupService.restoreOnlyNewData(backup: anyNamed('backup')))
          .thenAnswer((_) async => changesCount);

      // Create a list to capture emitted messages
      final List<BackupSyncMessage?> emittedMessages = [];

      // Listen to the stream and add messages to the list
      final subscription = backupImporterService.message.listen(emittedMessages.add);

      // Call the method under test
      final result = await backupImporterService.start(testBackupObject);

      // Wait for all expected asynchronous operations to complete.
      // This is crucial for stream testing with async methods.
      await Future.microtask(() {}); // Allow microtasks to run
      await Future.delayed(Duration.zero); // Allow event loop to process

      // Cancel the subscription to stop listening
      await subscription.cancel();

      expect(result, isTrue);
      verify(mockRestoreBackupService.restoreOnlyNewData(backup: testBackupObject)).called(1);

      // Now assert the emitted messages in order
      expect(emittedMessages.length, 2);

      // First message: processing
      expect(emittedMessages[0], isA<BackupSyncMessage>());
      expect(emittedMessages[0]!.processing, isTrue);
      expect(emittedMessages[0]!.success, isTrue);
      expect(emittedMessages[0]!.message, isNull);

      // Second message: success with changes count
      expect(emittedMessages[1], isA<BackupSyncMessage>());
      expect(emittedMessages[1]!.processing, isFalse);
      expect(emittedMessages[1]!.success, isTrue);
      expect(emittedMessages[1]!.message, '$changesCount records are imported or updated.');
    });

    test('reset should emit null', () async {
      // Create a completer to know when the null message has been received
      final completer = Completer<void>();

      // Listen to the stream and complete the completer when null is emitted
      backupImporterService.message.listen(expectAsync1((message) {
        expect(message, isNull);
        completer.complete();
      }));

      // Call the reset method
      backupImporterService.reset();

      // Wait for the completer to complete
      await completer.future;
    });
  });
}
