import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:storypad/app_theme.dart';

class SpIcons {
  SpIcons._(this.cupertino);

  final bool cupertino;
  static SpIcons of(BuildContext context) => SpIcons._(AppTheme.isCupertino(context));

  IconData get newStory => cupertino ? CupertinoIcons.pencil_outline : Icons.edit;
  IconData get edit => cupertino ? CupertinoIcons.square_pencil : Icons.edit_outlined;
  IconData get question => cupertino ? CupertinoIcons.question : Icons.question_mark_outlined;
  IconData get policy => cupertino ? CupertinoIcons.lock_shield : Icons.policy_outlined;
  IconData get onboarding => cupertino ? CupertinoIcons.today : Icons.waving_hand_outlined;
  IconData get license => MdiIcons.license;
  IconData get code => cupertino ? CupertinoIcons.chevron_left_slash_chevron_right : Icons.code;
  IconData get star => cupertino ? CupertinoIcons.star : Icons.star_border;
  IconData get starFilled => cupertino ? CupertinoIcons.star_fill : Icons.star;
  IconData get share => cupertino ? CupertinoIcons.share : Icons.ios_share_outlined;
  IconData get search => cupertino ? CupertinoIcons.search : Icons.search;
  IconData get tag => cupertino ? CupertinoIcons.tag : Icons.sell_outlined;
  IconData get archive => cupertino ? CupertinoIcons.archivebox : Icons.archive_outlined;
  IconData get theme => cupertino ? CupertinoIcons.paintbrush : Icons.color_lens_outlined;
  IconData get lock => cupertino ? CupertinoIcons.lock : Icons.lock_outline;
  IconData get photo => cupertino ? CupertinoIcons.photo : Icons.photo_album_outlined;
  IconData get cloudUpload => cupertino ? CupertinoIcons.cloud_upload : Icons.backup_outlined;
  IconData get googleDrive => MdiIcons.googleDrive;
  IconData get cloudDone => Icons.cloud_done_outlined;
  IconData get cloudOff => MdiIcons.cloudOff;
  IconData get pinSlash => cupertino ? CupertinoIcons.pin_slash : MdiIcons.pinOff;
  IconData get pin => cupertino ? CupertinoIcons.pin : MdiIcons.pin;
  IconData get bookLock => cupertino ? CupertinoIcons.book : MdiIcons.bookLockOutline;
  IconData get book => cupertino ? CupertinoIcons.book : MdiIcons.bookOutline;
  IconData get tune => cupertino ? CupertinoIcons.slider_horizontal_3 : MdiIcons.tuneVariant;
  IconData get forum => cupertino ? CupertinoIcons.bubble_left_bubble_right : Icons.forum_outlined;
  IconData get managingPage => cupertino ? CupertinoIcons.book_fill : MdiIcons.bookOpen;
  IconData get managingPageOff => cupertino ? CupertinoIcons.book : MdiIcons.bookOpenOutline;
  IconData get info => cupertino ? CupertinoIcons.info : Icons.info_outline;
  IconData get moreVert => cupertino ? CupertinoIcons.ellipsis_vertical : Icons.more_vert;
  IconData get save => cupertino ? CupertinoIcons.floppy_disk : Icons.save;
  IconData get addFeeling => Icons.add_reaction_sharp;
  IconData get favoriteFilled => cupertino ? CupertinoIcons.heart_fill : Icons.favorite;
  IconData get favorite => cupertino ? CupertinoIcons.heart : Icons.favorite_outline_outlined;
  IconData get bookmarkFilled => cupertino ? CupertinoIcons.bookmark_fill : Icons.bookmark_rounded;
  IconData get bookmark => cupertino ? CupertinoIcons.bookmark_fill : Icons.bookmark_outline_rounded;
  IconData get biometrics => Icons.face_unlock_outlined;
  IconData get faceUnlock => Icons.face_unlock_outlined;
  IconData get fingerprint => Icons.fingerprint_outlined;
  IconData get lockQuestion => cupertino ? CupertinoIcons.question_circle : MdiIcons.lockQuestion;
  IconData get keyboardRight => cupertino ? CupertinoIcons.right_chevron : Icons.keyboard_arrow_right;
  IconData get folderOpen => cupertino ? CupertinoIcons.folder_open : Icons.folder_open;
  IconData get profile => cupertino ? CupertinoIcons.person : Icons.person;
  IconData get delete => cupertino ? CupertinoIcons.delete : Icons.delete_outline;
  IconData get deleteForever => cupertino ? CupertinoIcons.bin_xmark : Icons.delete_forever;
  IconData get swapHoriz => cupertino ? CupertinoIcons.arrow_right_arrow_left : Icons.swap_horiz;
  IconData get putBack => cupertino ? CupertinoIcons.arrow_down_circle : Icons.settings_backup_restore;
  IconData get import => cupertino ? CupertinoIcons.cloud_download : Icons.restore_outlined;
  IconData get backspace => cupertino ? CupertinoIcons.delete_left : Icons.backspace;
  IconData get clear => cupertino ? CupertinoIcons.clear : Icons.clear;
  IconData get check => cupertino ? CupertinoIcons.check_mark : Icons.done;
  IconData get compare => cupertino ? CupertinoIcons.doc_on_doc : Icons.compare;
  IconData get draftEdit => cupertino ? CupertinoIcons.doc_on_doc : Icons.edit_note;
  IconData get checkbox => cupertino ? CupertinoIcons.check_mark_circled : Icons.check_box;
  IconData get checkboxBlank => cupertino ? CupertinoIcons.circle : Icons.check_box_outline_blank;
  IconData get expandMore => cupertino ? CupertinoIcons.chevron_down : Icons.expand_more_outlined;
  IconData get table => cupertino ? CupertinoIcons.doc_text_search : MdiIcons.table;
  IconData get restore => cupertino ? CupertinoIcons.doc_checkmark : MdiIcons.restore;
  IconData get checkCircle => cupertino ? CupertinoIcons.check_mark_circled : Icons.check_circle_outline;
  IconData get exploreBrowser => cupertino ? CupertinoIcons.globe : Icons.travel_explore_outlined;
  IconData get darkMode => cupertino ? CupertinoIcons.moon : Icons.dark_mode_outlined;
  IconData get lightMode => cupertino ? CupertinoIcons.sun_min : Icons.light_mode_outlined;
  IconData get font => cupertino ? CupertinoIcons.textbox : Icons.font_download_outlined;
  IconData get fontWeight => cupertino ? CupertinoIcons.textformat_size : Icons.format_size_outlined;
  IconData get warning => cupertino ? CupertinoIcons.exclamationmark : Icons.error_outline;
  IconData get refresh => cupertino ? CupertinoIcons.refresh : Icons.refresh;
  IconData get calendar => cupertino ? CupertinoIcons.calendar : Icons.calendar_month;
  IconData get exportOffline => cupertino ? CupertinoIcons.arrow_down_doc : Icons.download;
  IconData get importOffline => cupertino ? CupertinoIcons.arrow_up_doc : Icons.folder_open;
  IconData get update => cupertino ? CupertinoIcons.arrow_down : Icons.system_update;
  IconData get keyboardDown => cupertino ? CupertinoIcons.chevron_down : Icons.keyboard_arrow_down_outlined;
  IconData get dropDown => cupertino ? CupertinoIcons.chevron_down : Icons.arrow_drop_down;
  IconData get globe => cupertino ? CupertinoIcons.globe : Icons.language;
  IconData get add => cupertino ? CupertinoIcons.plus : Icons.add;
  IconData get factCheck => cupertino ? CupertinoIcons.text_badge_checkmark : Icons.fact_check_outlined;
  IconData get dragIndicator => Icons.drag_indicator;
  IconData get imageNotSupported => cupertino ? CupertinoIcons.flag_slash : Icons.image_not_supported_outlined;
  IconData get addPhoto => cupertino ? CupertinoIcons.add : Icons.add_a_photo;
  IconData get hideSource => cupertino ? CupertinoIcons.circle : Icons.hide_source;
}
