// GENERATED FILE - DO NOT MODIFY
// This file is auto-generated by bin/update_app_logo
// To add or remove logos, modify the script or update assets/logos/ directory

import 'package:storypad/gen/assets.gen.dart';

enum AppLogo {
  storypad_1_0(logoName: 'storypad_logo_1_0'),
  storypad_2_0(logoName: 'storypad_logo_2_0'),
  storypad_3_0(logoName: 'storypad_logo_3_0'),
  storypad_4_0(logoName: 'storypad_logo_4_0'),
  storypad_5_0(logoName: 'storypad_logo_5_0'),
  storypad_6_0(logoName: 'storypad_logo_6_0'),
  storypad_6_1(logoName: 'storypad_logo_6_1')
  ;

  final String logoName;

  String get xcodeLogoName => logoName;
  String get androidActivityAliasName => 'com.tc.writestory.$logoName';

  const AppLogo({
    required this.logoName,
  });

  AssetGenImage get asset {
    switch (this) {
      case .storypad_1_0:
        return Assets.logos.storypadLogo10.assets.storypadLogo10;
      case .storypad_2_0:
        return Assets.logos.storypadLogo20.assets.storypadLogo20;
      case .storypad_3_0:
        return Assets.logos.storypadLogo30.assets.storypadLogo30;
      case .storypad_4_0:
        return Assets.logos.storypadLogo40.assets.storypadLogo40;
      case .storypad_5_0:
        return Assets.logos.storypadLogo50.assets.storypadLogo50;
      case .storypad_6_0:
        return Assets.logos.storypadLogo60.assets.storypadLogo60;
      case .storypad_6_1:
        return Assets.logos.storypadLogo61.assets.storypadLogo61;
    }
  }
}
