// Generated by bin/localization/build.dart
import 'dart:ui';

const kFallbackLocale = Locale("en");

const kSupportedLocales = [
  Locale("en"),
  Locale("ar"),
  Locale("de", "DE"),
  Locale("es", "419"),
  Locale("es", "ES"),
  Locale("fr", "FR"),
  Locale("hi", "IN"),
  Locale("id"),
  Locale("it", "IT"),
  Locale("ja", "JP"),
  Locale("km"),
  Locale("ko", "KR"),
  Locale("pl", "PL"),
  Locale("pt", "BR"),
  Locale("vi", "VN"),
  Locale("zh", "CN")
];

const kLanguageNames = {
  "en": "English",
  "ar": "Arabic",
  "de-DE": "German (Germany)",
  "es-419": "Spanish (Latin America)",
  "es-ES": "Spanish (Spain)",
  "fr-FR": "French (France)",
  "hi-IN": "Hindi (India)",
  "id": "Indonesian",
  "it-IT": "Italian (Italy)",
  "ja-JP": "Japanese (Japan)",
  "km": "Khmer",
  "ko-KR": "Korean (South Korea)",
  "pl-PL": "Polish (Poland)",
  "pt-BR": "Portuguese (Brazil)",
  "vi-VN": "Vietnamese (Vietnam)",
  "zh-CN": "Chinese (Simplified)"
};

const kNativeLanguageNames = {
  "en": "English",
  "ar": "العربية",
  "de-DE": "Deutsch (Deutschland)",
  "es-419": "Español (Latinoamérica)",
  "es-ES": "Español (España)",
  "fr-FR": "Français (France)",
  "hi-IN": "हिन्दी (भारत)",
  "id": "Bahasa Indonesia",
  "it-IT": "Italiano (Italia)",
  "ja-JP": "日本語 (日本)",
  "km": "ភាសាខ្មែរ",
  "ko-KR": "한국어 (대한민국)",
  "pl-PL": "Polski (Polska)",
  "pt-BR": "Português (Brasil)",
  "vi-VN": "Tiếng Việt (Việt Nam)",
  "zh-CN": "中文 (简体)"
};
